### ISSUE TITLE
Fix error of alignment

### ISSUE THREAD

**Issue by monambike** [monambike/monambike.github.io#26]
The header should display elements inline, what is not happening at following.

![error-align](https://user-images.githubusercontent.com/35270174/92361233-7f680080-f0c4-11ea-880e-6fe1d6260747.png)

This is probably happening because the inline-block property must to be in the ul, not in the li.

In `css/styleheader.css`, the code:
```css
li{
	color: var(--purple-1);
	display: inline-block;
	list-style: none;
	margin: 0px;
	padding: 2%;
}
```
should be:
```css
ul{
	display: inline-block;
}
li{
	color: var(--purple-1);
	list-style: none;
	margin: 0px;
	padding: 2%;
}
```
